Prefer KeyError to nil pointer error
Because the message on a key error is more useful for debugging.

Compare:
```
     KeyError:
       key not found: "internal_resource_ssim"
```

to

```
     NoMethodError:
       undefined method `first' for nil:NilClass
```

Also removed unnecessary cleaning of solr id field.