raise a more informative NoMethodError for missing custom queries
the custom query container used to raise:

    NoMethodError: undefined method 'new' for nil:NilClass`

this error doesn't do much to help callers figure out where they've gone
awry. the updated message includes:

  - the originally called method name
  - the list of available methods to call (as a kind of 'did you mean' feature)
  - reference to the idea that queries need to be registered

hopefully these are all helpful reminders in dubugging.