Ensuring find_by_alternate_identifier works without alternate_ids
Prior to this commit, with the committed spec, you would get the
following error:

```console
expected Valkyrie::Persistence::ObjectNotFoundError, got #<NoMethodError: undefined method `include?' for nil:NilClass> with backtrace:
         # ./lib/valkyrie/persistence/memory/query_service.rb:40:in `block in find_by_alternate_identifier'
         # ./lib/valkyrie/persistence/memory/query_service.rb:39:in `select'
         # ./lib/valkyrie/persistence/memory/query_service.rb:39:in `find_by_alternate_identifier'
         # ./lib/valkyrie/specs/shared_specs/queries.rb:97:in `block (4 levels) in <top (required)>'
         # ./lib/valkyrie/specs/shared_specs/queries.rb:97:in `block (3 levels) in <top (required)>'

Shared Example Group: "a Valkyrie query provider" called from ./spec/valkyrie/persistence/memory/query_service_spec.rb:7
```

This commit skips records that don't have an alternate_ids attribute.

Fixes #657